---
#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to master #
#######################################
name: "Build & Deploy - Beta"
on:
  push:
    branches:
      - "master"

##############################
# Deploy beta version on NPM #
##############################
jobs:
  deploy:
    name: Deploy beta
    runs-on: ubuntu-latest
    permissions: read-all
    environment:
      name: beta
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          always-auth: true
          # Defaults to the user or organization that owns the workflow file
          scope: "rubenhalman"
      - run: yarn
      - run: yarn config set version-git-tag false && tsc -b
      - run: BETAID=$(date '+%Y%m%d%H%M') && yarn version --prepatch --preid="beta$BETAID"
      - run: yarn config set network-timeout 300000 && yarn publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

